---
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['{{ ansible_host }}:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['{{ ansible_host }}:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['{{ ansible_host }}:8090']

  - job_name: 'docker'
    static_configs:
      - targets: ['{{ ansible_host }}:9323']

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['{{ ansible_host }}:9187']
