global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['{{ ansible_host }}:9090']
    relabel_configs:
      - source_labels: [__address__]
        target_label: real_host
      - source_labels: [__address__]
        regex: '([^:]+):.*'
        target_label: host_ip
        replacement: '${1}'
      - target_label: prometheus_server
        replacement: 'prometheus-main'
      - target_label: service_type
        replacement: 'prometheus'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['{{ ansible_host }}:9100']
    relabel_configs:
      - source_labels: [__address__]
        target_label: real_host
      - source_labels: [__address__]
        regex: '([^:]+):.*'
        target_label: host_ip
        replacement: '${1}'
      - target_label: prometheus_server
        replacement: 'prometheus-main'
      - target_label: service_type
        replacement: 'node-metrics'
      - target_label: environment
        replacement: 'production'
    metric_relabel_configs:
      - source_labels: [instance]
        target_label: original_instance

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['{{ ansible_host }}:8090']
    relabel_configs:
      - source_labels: [__address__]
        target_label: real_host
      - source_labels: [__address__]
        regex: '([^:]+):.*'
        target_label: host_ip
        replacement: '${1}'
      - target_label: prometheus_server
        replacement: 'prometheus-main'
      - target_label: service_type
        replacement: 'container-metrics'
      - target_label: environment
        replacement: 'production'
    metric_relabel_configs:
      - source_labels: [instance]
        target_label: original_instance
      - source_labels: [container_name]
        target_label: container
        regex: '(.+)'

  - job_name: 'docker'
    static_configs:
      - targets: ['{{ ansible_host }}:9323']
    relabel_configs:
      - source_labels: [__address__]
        target_label: real_host
      - source_labels: [__address__]
        regex: '([^:]+):.*'
        target_label: host_ip
        replacement: '${1}'
      - target_label: prometheus_server
        replacement: 'prometheus-main'
      - target_label: service_type
        replacement: 'docker-metrics'
      - target_label: environment
        replacement: 'production'
    metric_relabel_configs:
      - source_labels: [instance]
        target_label: original_instance

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['{{ ansible_host }}:9187']
    relabel_configs:
      - source_labels: [__address__]
        target_label: real_host
      - source_labels: [__address__]
        regex: '([^:]+):.*'
        target_label: host_ip
        replacement: '${1}'
      - target_label: prometheus_server
        replacement: 'prometheus-main'
      - target_label: service_type
        replacement: 'postgres-metrics'
      - target_label: environment
        replacement: 'production'
    metric_relabel_configs:
      - source_labels: [instance]
        target_label: original_instance
      - source_labels: [datname]
        target_label: database
        regex: '(.+)'

